services:
  photo-service-gui:
    build: .
    image: ghcr.io/langrenn-sprint/photo-service-gui:test
    ports:
      - 8080:8080
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_PHOTO_CREDENTIALS_FILE=${GOOGLE_PHOTO_CREDENTIALS_FILE}
      - GOOGLE_PUBSUB_SUBSCRIPTION_ID=${GOOGLE_PUBSUB_SUBSCRIPTION_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_PUBSUB_NUM_MESSAGES=${GOOGLE_PUBSUB_NUM_MESSAGES}
      - GOOGLE_PUBSUB_TOPIC_ID==${GOOGLE_PUBSUB_TOPIC_ID}
      - GOOGLE_PUBSUB_SUBSCRIPTION_ID==${GOOGLE_PUBSUB_SUBSCRIPTION_ID}
      - GOOGLE_STORAGE_BUCKET==${GOOGLE_STORAGE_BUCKET}
      - GOOGLE_STORAGE_SERVER==${GOOGLE_STORAGE_SERVER}
      - HOST_PORT=8080
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - PHOTOS_HOST_SERVER=photo-service
      - PHOTOS_HOST_PORT=8080
      - EVENTS_HOST_SERVER=event-service
      - EVENTS_HOST_PORT=8080
      - COMPETITION_FORMAT_HOST_SERVER=competition-format-service
      - COMPETITION_FORMAT_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
    volumes:
      - type: bind
        source: ./error.log
        target: /app/error.log
    depends_on:
      - event-service
      - photo-service
      - user-service
      - mongodb
  event-service:
    image: ghcr.io/langrenn-sprint/event-service:latest
    ports:
      - 8082:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - COMPETITION_FORMAT_HOST_SERVER=competition-format-service
      - COMPETITION_FORMAT_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - user-service
      - mongodb
  competition-format-service:
    image: ghcr.io/langrenn-sprint/competition-format-service:latest
    ports:
      - 8094:8080
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
      - user-service
      - mongodb
  photo-service:
    image: ghcr.io/langrenn-sprint/photo-service:latest
    ports:
      - 8092:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - GOOGLE_PHOTO_SERVER=https://photoslibrary.googleapis.com/v1
      - GOOGLE_PHOTO_SCOPE=https://www.googleapis.com/auth/photoslibrary.readonly
      - GOOGLE_PHOTO_CREDENTIALS_FILE=/home/heming/github/photo_api_credentials.json
      - SERVICEBUS_NAMESPACE_CONNECTION_STR=${SERVICEBUS_NAMESPACE_CONNECTION_STR}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - user-service
      - mongodb
  user-service:
    image: ghcr.io/langrenn-sprint/user-service:latest
    ports:
      - 8086:8080
    environment:
      - JWT_EXP_DELTA_SECONDS=${JWT_EXP_DELTA_SECONDS}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
