version: '3'
services:
  photo-service-gui:
    build: .
    image: ghcr.io/langrenn-sprint/photo-service-gui:test
    ports:
      - 8090:8080
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_PHOTO_CREDENTIALS_FILE=${GOOGLE_PHOTO_CREDENTIALS_FILE}
      - GOOGLE_PUBSUB_SUBSCRIPTION_ID=${GOOGLE_PUBSUB_SUBSCRIPTION_ID}
      - HOST_PORT=8080
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - PHOTOS_HOST_SERVER=photo-service
      - PHOTOS_HOST_PORT=8080
    volumes:
      - type: bind
        source: .
        target: /app
