"""Package for all views."""
from .liveness import Ping
from .login import Login
from .logout import Logout
from .main import Main
from .photo_push import PhotoPush
from .photo_sync import PhotoSync
from .photo_update import PhotoUpdate
from .photos_adm import PhotosAdm
from .photos_edit import PhotosEdit
from .video_events import VideoEvents
